name: Build

on:
  push:

permissions:
  contents: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      package_version: ${{ steps.baipp.outputs.package_version }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@c52c3a4710070b50470d903818a7b25115dcd076 # v2.13.0
        id: baipp

  publish:
    runs-on: ubuntu-24.04
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/${{ needs.build.outputs.package_name }}/${{ needs.build.outputs.package_version }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: Packages
          path: dist
      - uses: svenstaro/upload-release-action@cd8e7cbf67456e30da904d9dd06c146632cb868c # 2.9.1
        with:
          file: dist/*.whl
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
